import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { firebaseConfig } from "./firebase-config.js";

const appEl=document.getElementById("adminApp");
let db=null,auth=null,data=null;
let firebaseApp=null;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function configured(){return firebaseConfig.apiKey&&!firebaseConfig.apiKey.startsWith("여기에")}
function defaultData(){return {generations:{1:[],2:[],3:[],4:[]},tiers:[],story:{title:"SCP FRIEND UNIVERSE",body:""},events:[],updates:[]}}
function showLogin(msg=""){appEl.innerHTML=`<section class="panel login"><h1>⚙ 관리자</h1><div class="notice">Firebase에 등록된 관리자 이메일과 비밀번호로 로그인하세요.</div><div class="field"><label>이메일</label><input id="email" type="email" autocomplete="username"></div><div class="field"><label>비밀번호</label><input id="pw" type="password" autocomplete="current-password"></div><button class="primary" id="login">로그인</button><p id="msg" class="small error">${esc(msg)}</p><p class="small"><a href="index.html">← 사이트로 돌아가기</a></p></section>`;document.getElementById("login").onclick=async()=>{const email=document.getElementById("email").value.trim(),pw=document.getElementById("pw").value;const m=document.getElementById("msg");m.textContent="로그인 중...";try{await signInWithEmailAndPassword(auth,email,pw)}catch(e){m.textContent="이메일 또는 비밀번호가 올바르지 않습니다."}};document.getElementById("pw").addEventListener("keydown",e=>{if(e.key==="Enter")document.getElementById("login").click()})}
async function load(){try{const snap=await get(ref(db,"database"));data=snap.exists()?snap.val():defaultData();editor()}catch(e){appEl.innerHTML=`<section class="panel"><h1>연결 오류</h1><p class="error">${esc(e.message)}</p></section>`}}
function editor(){appEl.innerHTML=`<section class="panel"><h1>관리자</h1><p class="small">저장하면 Firebase 데이터가 바로 변경됩니다.</p><div class="admin-tabs"><button id="scpTab">SCP 관리</button><button id="tierTab">티어표</button><button id="storyTab">세계관</button><button id="eventTab">사건</button><button id="logout">로그아웃</button></div></section><div id="editor"></div>`;document.getElementById("scpTab").onclick=scps;document.getElementById("tierTab").onclick=tiers;document.getElementById("storyTab").onclick=story;document.getElementById("eventTab").onclick=events;document.getElementById("logout").onclick=async()=>{await signOut(auth);};scps()}
function scps(){const ed=document.getElementById("editor");let html='<section class="panel"><h2>SCP 관리</h2>';for(let n=1;n<=4;n++){html+=`<h3>${n}세대</h3><div class="grid">`;for(const x of (data.generations?.[n]||[])){html+=`<div class="card"><div class="code">${esc(x.id)}</div><div class="title">${esc(x.name)}</div><div class="row"><button class="secondary" data-edit="${esc(x.id)}">수정</button><button class="danger" data-del="${esc(x.id)}">삭제</button></div></div>`}html+=`</div><button class="primary" data-add="${n}" style="margin:10px 0 18px">+ ${n}세대 SCP 추가</button>`}html+='</section>';ed.innerHTML=html;ed.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>form(null,+b.dataset.add));ed.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>form(find(b.dataset.edit)));ed.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>del(b.dataset.del))}
function find(id){for(const [n,g] of Object.entries(data.generations||{})){const x=(g||[]).find(a=>a.id===id);if(x)return {...x,__gen:+n}}return null}
function form(x,gen){const ed=document.getElementById("editor"),a=x||{id:"",name:"",risk:"",containment:"",description:"",abilities:[],defense:[],future:[],ultimate:"",quote:""};ed.innerHTML=`<section class="panel"><h2>${x?"SCP 수정":"SCP 추가"}</h2><div class="field"><label>세대</label><select id="gen">${[1,2,3,4].map(n=>`<option ${((x?.__gen||gen)===n)?"selected":""}>${n}</option>`)}</select></div>${field("id","SCP 번호",a.id)}${field("name","이름",a.name)}${field("risk","위험 등급",a.risk)}${field("containment","격리 상태",a.containment)}${area("description","설명",a.description)}${area("abilities","능력 (한 줄에 하나)",(a.abilities||[]).join("\n"))}${area("defense","방어 (한 줄에 하나)",(a.defense||[]).join("\n"))}${area("future","미래 관련 능력 (선택)",(a.future||[]).join("\n"))}${area("ultimate","궁극기",a.ultimate)}${area("quote","인용문",a.quote)}<div class="row"><button class="primary" id="save">저장</button><button class="secondary" id="cancel">취소</button></div></section>`;ed.querySelector("#save").onclick=async()=>{const v={id:g("id"),name:g("name"),risk:g("risk"),containment:g("containment"),description:g("description"),abilities:lines(g("abilities")),defense:lines(g("defense")),future:lines(g("future")),ultimate:g("ultimate"),quote:g("quote")};if(!v.id||!v.name){alert("SCP 번호와 이름은 입력해야 합니다.");return}const old=x?.id;if(old&&old!==v.id){const og=x.__gen;data.generations[og]=(data.generations[og]||[]).filter(q=>q.id!==old)}const ng=+document.getElementById("gen").value;data.generations[ng]=data.generations[ng]||[];data.generations[ng]=data.generations[ng].filter(q=>q.id!==v.id);data.generations[ng].push(v);await save("SCP "+(x?"수정":"추가")+": "+v.name);scps()};ed.querySelector("#cancel").onclick=scps}
function field(id,label,val){return `<div class="field"><label>${label}</label><input id="${id}" value="${esc(val)}"></div>`}function area(id,label,val){return `<div class="field"><label>${label}</label><textarea id="${id}">${esc(val)}</textarea></div>`}function g(id){return document.getElementById(id).value}function lines(s){return s.split("\n").map(x=>x.trim()).filter(Boolean)}
async function del(id){if(!confirm("삭제할까요?"))return;for(const n of [1,2,3,4])data.generations[n]=(data.generations[n]||[]).filter(x=>x.id!==id);await save("SCP 삭제: "+id);scps()}
function tiers(){const ed=document.getElementById("editor");ed.innerHTML=`<section class="panel"><h2>실시간 티어표</h2><p class="small">한 줄 형식: S+|SCP-JSI-000,SCP-TCJ-999</p><div class="field"><textarea id="tierText" style="min-height:220px">${esc((data.tiers||[]).map(t=>`${t.tier}|${(t.items||[]).join(",")}`).join("\n"))}</textarea></div><button class="primary" id="saveTier">저장</button></section>`;document.getElementById("saveTier").onclick=async()=>{data.tiers=document.getElementById("tierText").value.split("\n").map(l=>l.split("|")).filter(a=>a[0]).map(a=>({tier:a[0].trim(),items:(a[1]||"").split(",").map(x=>x.trim()).filter(Boolean)}));await save("티어표 수정")}}
function story(){const ed=document.getElementById("editor"),s=data.story||{};ed.innerHTML=`<section class="panel"><h2>세계관</h2>${field("title","제목",s.title||"")}${area("body","내용",s.body||"")}<button class="primary" id="saveStory">저장</button></section>`;document.getElementById("saveStory").onclick=async()=>{data.story={title:g("title"),body:g("body")};await save("세계관 수정")}}
function events(){const ed=document.getElementById("editor");ed.innerHTML=`<section class="panel"><h2>사건 기록</h2>${(data.events||[]).map((e,i)=>`<div class="ability"><b>${esc(e.title)}</b><br>${esc(e.body)}<br><div class="row"><button class="secondary" data-edit-event="${i}">수정</button><button class="danger" data-x="${i}">삭제</button></div></div>`).join("")||'<div class="empty">사건이 없습니다.</div>'}<hr>${field("et","사건 제목","")}${area("eb","사건 내용","")}<button class="primary" id="addEvent">사건 추가</button></section>`;ed.querySelectorAll("[data-x]").forEach(b=>b.onclick=async()=>{data.events.splice(+b.dataset.x,1);await save("사건 삭제");events()});ed.querySelectorAll("[data-edit-event]").forEach(b=>b.onclick=()=>eventForm(+b.dataset.editEvent));document.getElementById("addEvent").onclick=async()=>{const title=g("et").trim(),body=g("eb").trim();if(!title){alert("사건 제목을 입력하세요.");return}data.events=data.events||[];data.events.push({title,body});await save("사건 추가");events()})}
function eventForm(i){const e=data.events[i];const ed=document.getElementById("editor");ed.innerHTML=`<section class="panel"><h2>사건 수정</h2>${field("et","사건 제목",e.title||"")}${area("eb","사건 내용",e.body||"")}<div class="row"><button class="primary" id="saveEvent">저장</button><button class="secondary" id="cancelEvent">취소</button></div></section>`;document.getElementById("saveEvent").onclick=async()=>{data.events[i]={title:g("et"),body:g("eb")};await save("사건 수정");events()};document.getElementById("cancelEvent").onclick=events}
async function save(msg){data.updates=data.updates||[];data.updates.push({text:msg,time:new Date().toLocaleString("ko-KR")});await set(ref(db,"database"),data);alert("저장 완료! 실시간으로 반영됩니다.")}

if(!configured()){appEl.innerHTML='<section class="panel"><h1>Firebase 연결 필요</h1><p class="muted">firebase-config.js 설정을 확인하세요.</p></section>'}else{try{firebaseApp=initializeApp(firebaseConfig);db=getDatabase(firebaseApp);auth=getAuth(firebaseApp);onAuthStateChanged(auth,user=>{if(user)load();else showLogin()})}catch(e){appEl.innerHTML=`<section class="panel"><h1>초기화 오류</h1><p class="error">${esc(e.message)}</p></section>`}}
