import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, onValue } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";

const root=document.getElementById("app"), status=document.getElementById("status");
let db=null, data=null;
const demo={
  generations:{
    1:[{id:"SCP-JEC-001",name:"재민이의 눈",risk:"Ω — TRANSCENDENT",containment:"UNCONTAINABLE",description:"재민이의 초월적인 눈. 개안 단계가 높아질수록 우주적 힘이 폭발적으로 증가한다.",abilities:["개안 레이저 — 시선을 한 점에 집중해 고출력 광선을 발사한다.","패왕안 — 압도적인 시선으로 상대의 움직임과 전투 의지를 억제한다.","성운탄 — 빛을 구체로 압축한 뒤 충돌 지점에서 거대한 에너지를 방출한다.","중력안 — 바라보는 지점의 중력을 급격히 증가시킨다."],defense:["광막 — 압축된 빛으로 방어막을 만든다.","천체장 — 주변 에너지를 방어장으로 변환한다."],ultimate:"제1개안: 창세 — 눈을 완전히 개안해 공간을 빛으로 덮고 창세급 에너지를 방출한다. 사용 후 10초 동안 주력 개안 능력이 제한된다.",quote:"재민이가 눈을 뜨면, 파괴가 아니라 새로운 시작이 찾아온다."},
  {id:"SCP-STP-404",name:"시온이의 삼각팬티",risk:"Ω+ — TRANSCENDENT",containment:"UNCONTAINABLE",description:"삼각 구조와 가상의 변칙적 미생물 에너지가 결합된 힘. 이를 통칭해 '삼각무좀'이라 부른다.",abilities:["삼각무좀탄 — 삼각 에너지 공격이 충돌하면 세 갈래로 분열된다.","삼각천쇄 — 거대한 삼각형 구조를 연속으로 생성해 공격한다.","무좀 증식 — 남은 변칙 에너지가 새로운 삼각 구조로 증식한다.","삼각균열 — 삼각형 모양의 공간 균열을 만들고 균열을 따라 에너지를 폭발시킨다."],defense:["삼각 절대방벽 — 세 겹의 삼각 장벽이 충격을 여러 방향으로 분산한다."],ultimate:"삼각무좀: 무한증식 — 하나의 삼각형이 3, 9, 27, 81…로 증식하며 전장을 뒤덮는다. 사용 후 15초 동안 삼각 계열 능력이 크게 약화된다.",quote:"세 개의 점으로 시작했다. 하지만 마지막에는 셀 수 없는 삼각형이 되었다."},
  {id:"SCP-TCJ-999",name:"자비스",risk:"Ω∞ — TRANSCENDENT",containment:"UNCONTAINABLE",description:"태율의 자비스. 모든 힘은 자신의 몸에서 생성되는 가상의 백색 물질에서 나온다. 외부 소환이나 도구 없이 형태·속도·밀도·경도를 자유롭게 변화시킨다.",abilities:["화이트 블레이드 — 백색 물질을 고밀도로 경화해 빠르게 발사한다.","화이트 버스트 — 짧은 시간에 수십~수백 번의 연속 공격을 방출한다.","화이트 스나이퍼 — 극도로 얇고 단단하게 압축해 장거리 직선 공격을 한다.","화이트 크러셔 — 거대한 질량으로 압축해 강한 충격을 일으킨다.","화이트 드릴 — 회전하는 형태로 방출해 관통력을 높인다.","화이트 리코셰 — 단단한 표면에 튕겨 여러 방향으로 궤도를 바꾼다."],defense:["화이트 아머 — 몸 주변의 백색 물질을 고밀도로 굳혀 갑옷으로 만든다.","화이트 리커버리 — 손상된 방어 물질을 빠르게 복구한다."],ultimate:"JARVIS: WHITE APOCALYPSE — 저장된 백색 물질을 거의 전부 한 번에 압축해 초고속으로 방출한다. 첫 충격 뒤 추가 압력파가 발생한다. 사용 후 20초 동안 고출력 공격이 제한된다.",quote:"자비스는 하늘에서 힘을 부르지 않는다. 자비스의 모든 힘은 자신에게서 나온다."},
  {id:"SCP-JSI-000",name:"일루미나티",risk:"Ω∞ — TRANSCENDENT",containment:"UNCONTAINABLE",description:"재민의 눈과 시온의 삼각무좀 힘이 융합된 존재. 두 힘을 단순히 더하는 것이 아니라, 눈의 빛을 삼각 구조에 통과시켜 새로운 공격으로 변환한다.",abilities:["트라이앵글 아이 — 거대한 삼각형 중앙의 눈에서 세 방향으로 압축된 광선을 발사한다.","무좀 프리즘 — 삼각 구조가 빛을 수백 갈래로 분산해 전방을 뒤덮는다.","성운 삼각포 — 삼각 에너지 구체에 빛을 압축한 뒤 수천 개의 광창으로 펼친다.","개안 폭격 — 하늘에 여러 눈과 삼각 구조를 만들고 사방으로 삼각 광선을 발사한다.","삼각 초신성 — 거대한 삼각형 내부에 에너지를 압축한 뒤 초신성급 폭발로 붕괴시킨다."],defense:["일루미나티 프리즘 — 들어오는 공격을 삼각 구조로 분해해 여러 방향으로 굴절시킨다.","삼중 개안 — 세 개의 눈이 서로 다른 방향에서 방어막을 형성한다."],ultimate:"ILLUMINATI: LAST EYE — 하늘에 거대한 삼각형과 눈을 만들고 수천 개의 삼각 구조가 중앙의 눈에 에너지를 공급한다. 눈을 한 번 감았다 뜨는 순간 거대한 삼각 공간과 내부의 광선·변칙 에너지가 동시에 붕괴한다. 사용 후 30초 동안 공격과 미래 관측이 제한된다.",quote:"자비스는 미래를 예측하지 않는다. 일루미나티가 자비스가 패배하는 미래를 찾아낼 뿐이다.",future:["미래 관측 — 가능한 미래의 결과를 관측한다.","미래 고정 — 관측한 여러 가능성 중 하나를 선택해 그 결과가 일어나도록 만든다."]}]
  },
  tiers:[{tier:"S+",items:["SCP-JSI-000","SCP-TCJ-999"]},{tier:"S",items:["SCP-STP-404"]},{tier:"A",items:["SCP-JEC-001"]}],
  story:{title:"SCP FRIEND UNIVERSE",body:"이곳에 세계관의 시작과 세대별 역사를 작성하세요."},
  events:[], updates:[{text:"초기 1세대 SCP 4개 등록",time:"초기 데이터"}]
};
function safeConfig(){return firebaseConfig.apiKey && !firebaseConfig.apiKey.startsWith("여기에")}
function setData(v){data=v||demo; status.textContent=safeConfig()?"● 실시간 연결":"○ 데모 데이터"}
function renderHome(){root.innerHTML=`<section class="hero"><div class="eyebrow">SCP FRIEND UNIVERSE</div><h1>친구들의 세계관 데이터베이스</h1><p>세대, SCP, 스토리와 티어를 한 곳에서 확인하세요.</p></section><section class="panel"><h2>최근 업데이트</h2>${(data.updates||[]).slice().reverse().slice(0,8).map(x=>`<div class="update">${esc(x.text)} <span class="small">${esc(x.time||"")}</span></div>`).join("")||'<div class="empty">업데이트가 없습니다.</div>'}</section>`}
function renderGen(n){const list=data.generations?.[n]||[];root.innerHTML=`<button class="back" onclick="home()">← 홈</button><section class="panel"><div class="eyebrow">GENERATION ${n}</div><h1>${n}세대</h1><div class="grid">${list.map(x=>`<div class="card" onclick="detail('${escAttr(x.id)}')"><div class="code">${esc(x.id)}</div><div class="title">${esc(x.name)}</div><span class="pill">${esc(x.risk||"미정")}</span></div>`).join("")||'<div class="empty">아직 등록된 SCP가 없습니다.</div>'}</div></section>`}
function find(id){for(const g of Object.values(data.generations||{})){const x=(g||[]).find(a=>a.id===id);if(x)return x}return null}
function detail(id){const x=find(id);if(!x)return;root.innerHTML=`<button class="back" onclick="genFor('${escAttr(id)}')">← 목록</button><section class="panel detail"><div class="code">${esc(x.id)}</div><h1>「${esc(x.name)}」</h1><div><span class="pill">위험 ${esc(x.risk||"미정")}</span><span class="pill">격리 ${esc(x.containment||"미정")}</span></div><p class="muted">${esc(x.description||"")}</p><h2>능력</h2>${(x.abilities||[]).map(a=>`<div class="ability">${esc(a)}</div>`).join("")}<h2>방어</h2>${(x.defense||[]).map(a=>`<div class="ability">${esc(a)}</div>`).join("")}<h2>궁극기</h2><div class="ability">${esc(x.ultimate||"")}</div>${x.future?.length?`<h2>미래 관련 능력</h2>${x.future.map(a=>`<div class="ability">${esc(a)}</div>`).join("")}`:""}<h2>기록</h2><div class="ability">“${esc(x.quote||"기록된 인용문 없음")}”</div></section>`}
function genFor(id){for(const [n,g] of Object.entries(data.generations||{})){if((g||[]).some(x=>x.id===id)){renderGen(n);return}}}
function renderTier(){root.innerHTML=`<button class="back" onclick="home()">← 홈</button><section class="panel"><div class="eyebrow">LIVE POWER RANKING</div><h1>실시간 티어표</h1>${(data.tiers||[]).map(t=>`<div class="tier-row"><div class="tier-label">${esc(t.tier)}</div><div class="tier-items">${(t.items||[]).map(id=>{const x=find(id);return `<div class="tier-chip">${esc(x?.name||id)}</div>`}).join("")}</div></div>`).join("")||'<div class="empty">티어표가 없습니다.</div>'}</section>`}
function renderText(kind,title){const obj=data[kind]||{};root.innerHTML=`<button class="back" onclick="home()">← 홈</button><section class="panel"><div class="eyebrow">WORLD BUILDING</div><h1>${esc(obj.title||title)}</h1><div class="muted" style="white-space:pre-wrap;line-height:1.8">${esc(obj.body||"내용이 없습니다.")}</div></section>`}
function renderEvents(){root.innerHTML=`<button class="back" onclick="home()">← 홈</button><section class="panel"><h1>📜 사건 기록</h1>${(data.events||[]).map(e=>`<div class="ability"><b>${esc(e.title||"사건")}</b><br><span class="muted">${esc(e.body||"")}</span></div>`).join("")||'<div class="empty">기록된 사건이 없습니다.</div>'}</section>`}
function renderUpdates(){root.innerHTML=`<button class="back" onclick="home()">← 홈</button><section class="panel"><h1>📰 업데이트 기록</h1>${(data.updates||[]).slice().reverse().map(e=>`<div class="update">${esc(e.text)} <span class="small">${esc(e.time||"")}</span></div>`).join("")||'<div class="empty">업데이트가 없습니다.</div>'}</section>`}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function escAttr(s){return esc(s).replace(/`/g,"&#096;")}
window.home=renderHome;window.detail=detail;window.genFor=genFor;
document.getElementById("openMenu").onclick=()=>{document.getElementById("drawer").classList.add("open");document.getElementById("shade").classList.add("show")};
document.getElementById("closeMenu").onclick=()=>closeMenu();document.getElementById("shade").onclick=()=>closeMenu();
function closeMenu(){document.getElementById("drawer").classList.remove("open");document.getElementById("shade").classList.remove("show")}
document.querySelectorAll(".menu-item[data-view]").forEach(b=>b.onclick=()=>{closeMenu();const v=b.dataset.view;if(v==="generation")renderGen(b.dataset.gen);else if(v==="tier")renderTier();else if(v==="story")renderText("story","세계관 스토리");else if(v==="events")renderEvents();else if(v==="updates")renderUpdates()});
document.getElementById("adminBtn").onclick=()=>{closeMenu();location.href="admin.html"};
if(safeConfig()){try{const app=initializeApp(firebaseConfig);db=getDatabase(app);onValue(ref(db,"database"),snap=>{if(snap.exists()){setData(snap.val());renderHome()}else{setData(demo);renderHome()}});onValue(ref(db,"database"),()=>status.textContent="● 실시간 연결")}catch(e){setData(demo);status.textContent="○ 데모(설정 오류)";renderHome()}}else{setData(demo);renderHome()}
